### ISSUE TITLE
[Feature]: Create dedicated pages for the AR/VR subdomains

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#273]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/d9dcb990-a056-40a9-b630-ecba9d186fd5)

Create separate pages for: AR, VR, MR, Unity 3D, WebXR and connect them with the cards.
https://www.nsccbpit.tech/arvr

**Comment by iamrishiksahu** [comment]
@pradeeptosarkar I wish to work on this. I will be creating separate web pages for all of these cards and will connect them. Along with that, I am willing to add some dummy data into the newly created web pages so that It doesn't seems empty.

Kindly assign this issue to me so that I can proceed ahead immediately.

**Comment by pradeeptosarkar** [comment]
@iamrishiksahu sure buddy go ahead

**Comment by iamrishiksahu** [comment]
Thanks, I have started working on it!

**Comment by iamrishiksahu** [comment]
I have created total 5 Pages as follows:

1. Augmented Reality `/arvr/augmented-reality`
2. Virtual Reality `/arvr/virtual-reality`
3. Mixed Reality `/arvr/mixed-reality`
4. Unity 3D `/arvr/unity3d`
5. WebXR `/arvr/webxr`

In each page, I have added a basic center-aligned heading stating the title of the page and a "coming soon..." text just below that.

Here's an animated image depicting the final result:


![arvr-page-output](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/60431447/75f03131-239f-4f2d-9ff0-f2a3a786ff16)

I am looking forward for your suggestions @pradeeptosarkar

If not any, I will then make a pull request for these changes.

**Comment by pradeeptosarkar** [comment]
@iamrishiksahu can you also put up relevant content to these pages

**Comment by iamrishiksahu** [comment]
Yes sure, but can we create a new issue for that?

In my point of view, that would be a better practice in terms of documenting changes because the purpose of this issue has been fulfilled by the resolution done till now.

 If you allow, I'll create a new issue regarding the same otherwise, will proceed with making further changes in the same issue.

**Comment by pradeeptosarkar** [comment]
@iamrishiksahu cool I'm creating a new issue for that. You may raise a PR for this one

**Comment by iamrishiksahu** [comment]
Alright, I am creating a PR for this.
