### ISSUE TITLE
[Feature]: Programs page need beautification 

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#297]
### Is your feature request related to a problem? Please describe.

https://www.nsccbpit.tech/programs

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/d49eb9ee-2195-41c1-9bb3-8b27af03c751)

the programs is currently plain and simple. Any efforts in changing and improving the look and feel are welcome.!

**Comment by Dev-sAHSRAH** [comment]
I had already requested for it, but was informed that someone is working on it.
I'm happy to take it up.

And convert it to something like this:

Desktop View:
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/7c1f3795-b497-4642-98c1-9a74be53490e)

Mobile view:
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/a31d1a36-b27b-46a8-94a9-845baa8f1318)

**Comment by pradeeptosarkar** [comment]
@Dev-sAHSRAH cool go ahead

**Comment by iamrishiksahu** [comment]
@Dev-sAHSRAH I think you can make the text left-aligned instead of center-aligned. That would be more correct from UI perspective. Apart from that, make the background color of the card to Black and add a `shadow-cyan-300` class to the card. This will give an awesome shadow effect to it. Also, make the description text white and decrease the size a bit.

Good luck!

**Comment by Dev-sAHSRAH** [comment]
@iamrishiksahu great! Will work on that. 
Thanks

**Comment by Dev-sAHSRAH** [comment]
Hey!, I'm almost done with the task, but there's problem with the images uploaded. Someone has rounded the images before hand and used them.  Because of which the rounded corners are appearing white.

Reference:
![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/97530701/cac772f7-c242-4916-8703-356ad64459ad)

Can someone upload the original images or suggest me the changes for the same?

**Comment by pradeeptosarkar** [comment]
its fine @Dev-sAHSRAH as of now. thanks for contributing :)
