### ISSUE TITLE
[Feature]: Dedicated page for Augmented Reality

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#303]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/5cf2124e-602a-49b5-ac62-50297acf4cd5)

https://www.nsccbpit.tech/arvr/augmented-reality

Add content to this page.!
Inspiration can be taken from other sub-domain pages.!

**Comment by iamrishiksahu** [comment]
I have looked up the pages from webd sub-domain. I am taking inspiration from the HTML and CSS pages.

Here is the example of the template which I will be using to create this page. 

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/60431447/b942473b-ecbb-484a-b8d9-be0c15a33119)

@pradeeptosarkar Please assign this issue to me, so that I can start working on it.

**Comment by pradeeptosarkar** [comment]
@iamrishiksahu go ahead

**Comment by iamrishiksahu** [comment]
I have created a PR  #323 for this issue. Kindly review that.

**Comment by pradeeptosarkar** [comment]
resolved
