### ISSUE TITLE
[Feature]: Dedicated page for Mixed Reality

### ISSUE THREAD

**Issue by pradeeptosarkar** [NSCC-BPIT/NSCC-BPIT-Website#305]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/50446690/d658209d-47ed-4b08-b6d7-81750a4af5ff)

https://www.nsccbpit.tech/arvr/mixed-reality

Add content to this page.!
Inspiration can be taken from other sub-domain pages.!

**Comment by iamrishiksahu** [comment]
I have looked up the pages from webd sub-domain. I am taking inspiration from the HTML and CSS pages.

Here is the example of the template which I will be using to create this page. 

![image](https://github.com/NSCC-BPIT/NSCC-BPIT-Website/assets/60431447/b942473b-ecbb-484a-b8d9-be0c15a33119)

@pradeeptosarkar Please assign this issue to me, so that I can start working on it.

**Comment by pradeeptosarkar** [comment]
@iamrishiksahu go ahead

**Comment by mnnkhndlwl** [comment]
@iamrishiksahu are you still working on this issue

**Comment by iamrishiksahu** [comment]
Yes I am, I will update it by eod.

**Comment by Rehan52004** [comment]
i want to work on it, please assign to me this issue.

**Comment by iamrishiksahu** [comment]
@Rehan52004 please go ahead, you can take this from me and get it assigned.
